/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class V0AndroidKeystoreFileUploadParams {
    'alias'?: string;
    'password'?: string;
    'privateKeyPassword'?: string;
    'uploadFileName'?: string;
    'uploadFileSize'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "alias",
            "baseName": "alias",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "privateKeyPassword",
            "baseName": "private_key_password",
            "type": "string"
        },
        {
            "name": "uploadFileName",
            "baseName": "upload_file_name",
            "type": "string"
        },
        {
            "name": "uploadFileSize",
            "baseName": "upload_file_size",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return V0AndroidKeystoreFileUploadParams.attributeTypeMap;
    }
}

