/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class V0AppWebhookResponseItemModel {
    'createdAt'?: string;
    'events'?: string;
    'headers'?: string;
    'registeredByAddon'?: boolean;
    'slug'?: string;
    'updatedAt'?: string;
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "string"
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "string"
        },
        {
            "name": "registeredByAddon",
            "baseName": "registered_by_addon",
            "type": "boolean"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0AppWebhookResponseItemModel.attributeTypeMap;
    }
}

