/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { AddonsPlan } from './addonsPlan';
import { AddonsSetupGuide } from './addonsSetupGuide';

export class V0AppAddOnResponseItemModel {
    'description'?: string;
    'documentationUrl'?: string;
    'hasUi'?: boolean;
    'icon'?: string;
    'id'?: string;
    'isBeta'?: boolean;
    'plan'?: AddonsPlan;
    'setupGuide'?: AddonsSetupGuide;
    'summary'?: string;
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "documentationUrl",
            "baseName": "documentation_url",
            "type": "string"
        },
        {
            "name": "hasUi",
            "baseName": "has_ui",
            "type": "boolean"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "isBeta",
            "baseName": "is_beta",
            "type": "boolean"
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "AddonsPlan"
        },
        {
            "name": "setupGuide",
            "baseName": "setup_guide",
            "type": "AddonsSetupGuide"
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0AppAddOnResponseItemModel.attributeTypeMap;
    }
}

