/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { V0AppWebhookResponseItemModel } from './v0AppWebhookResponseItemModel';
import { V0PagingResponseModel } from './v0PagingResponseModel';

export class V0AppWebhookListResponseModel {
    'data'?: Array<V0AppWebhookResponseItemModel>;
    'paging'?: V0PagingResponseModel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<V0AppWebhookResponseItemModel>"
        },
        {
            "name": "paging",
            "baseName": "paging",
            "type": "V0PagingResponseModel"
        }    ];

    static getAttributeTypeMap() {
        return V0AppWebhookListResponseModel.attributeTypeMap;
    }
}

