/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class V0AppUploadParams {
    /**
    * The slug of the owner of the repository at the git provider
    */
    'gitOwner'?: string;
    /**
    * The slug of the repository at the git provider
    */
    'gitRepoSlug'?: string;
    /**
    * If `true` then the repository visibility setting will be public, in case of `false` it will be private
    */
    'isPublic'?: boolean;
    /**
    * The git provider you are using, it can be `github`, `bitbucket`, `gitlab`, `gitlab-self-hosted` or `custom`
    */
    'provider'?: string;
    /**
    * The URL of your repository
    */
    'repoUrl'?: string;
    /**
    * It has to be provided by legacy reasons and has to have the `git` value
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "gitOwner",
            "baseName": "git_owner",
            "type": "string"
        },
        {
            "name": "gitRepoSlug",
            "baseName": "git_repo_slug",
            "type": "string"
        },
        {
            "name": "isPublic",
            "baseName": "is_public",
            "type": "boolean"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string"
        },
        {
            "name": "repoUrl",
            "baseName": "repo_url",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0AppUploadParams.attributeTypeMap;
    }
}

