/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { V0OwnerAccountResponseModel } from './v0OwnerAccountResponseModel';

export class V0AppResponseItemModel {
    'avatarUrl'?: string;
    'isDisabled'?: boolean;
    'isPublic'?: boolean;
    'owner'?: V0OwnerAccountResponseModel;
    'projectType'?: string;
    'provider'?: string;
    'repoOwner'?: string;
    'repoSlug'?: string;
    'repoUrl'?: string;
    'slug'?: string;
    'status'?: number;
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avatarUrl",
            "baseName": "avatar_url",
            "type": "string"
        },
        {
            "name": "isDisabled",
            "baseName": "is_disabled",
            "type": "boolean"
        },
        {
            "name": "isPublic",
            "baseName": "is_public",
            "type": "boolean"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "V0OwnerAccountResponseModel"
        },
        {
            "name": "projectType",
            "baseName": "project_type",
            "type": "string"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string"
        },
        {
            "name": "repoOwner",
            "baseName": "repo_owner",
            "type": "string"
        },
        {
            "name": "repoSlug",
            "baseName": "repo_slug",
            "type": "string"
        },
        {
            "name": "repoUrl",
            "baseName": "repo_url",
            "type": "string"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0AppResponseItemModel.attributeTypeMap;
    }
}

