/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class V0AppFinishParams {
    /**
    * Which config to use `default-android-config`, `default-cordova-config`, `default-fastlane-config`, `default-ionic-config`, `default-ios-config`,`default-macos-config`, `default-react-native-config`, `default-xamarin-config`, `other-config` (default if parameter is not speficied)
    */
    'config'?: string;
    /**
    * Environment variables for the application workflows, e.g. {\"env1\":\"val1\",\"env2\":\"val2\"}
    */
    'envs'?: { [key: string]: string; };
    /**
    * config specification mode, has to be specified with `manual` value
    */
    'mode'?: string;
    /**
    * The slug of the organization, who will be the owner of the application, if it\'s not specified, then the authenticated user will be the owner
    */
    'organizationSlug'?: string;
    /**
    * The type of your project (`android`, `ios`, `cordova`, `other`, `xamarin`, `macos`, `ionic`, `react-native`, `fastlane`, null)
    */
    'projectType'?: string;
    /**
    * The id of the stack the application will be built (these can be found in the [system report](https://github.com/bitrise-io/bitrise.io/tree/master/system_reports) file names)
    */
    'stackId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "config",
            "baseName": "config",
            "type": "string"
        },
        {
            "name": "envs",
            "baseName": "envs",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "string"
        },
        {
            "name": "organizationSlug",
            "baseName": "organization_slug",
            "type": "string"
        },
        {
            "name": "projectType",
            "baseName": "project_type",
            "type": "string"
        },
        {
            "name": "stackId",
            "baseName": "stack_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0AppFinishParams.attributeTypeMap;
    }
}

