/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class V0ArtifactListElementResponseModel {
    'artifactMeta'?: string;
    'artifactType'?: string;
    'fileSizeBytes'?: number;
    'isPublicPageEnabled'?: boolean;
    'slug'?: string;
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "artifactMeta",
            "baseName": "artifact_meta",
            "type": "string"
        },
        {
            "name": "artifactType",
            "baseName": "artifact_type",
            "type": "string"
        },
        {
            "name": "fileSizeBytes",
            "baseName": "file_size_bytes",
            "type": "number"
        },
        {
            "name": "isPublicPageEnabled",
            "baseName": "is_public_page_enabled",
            "type": "boolean"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0ArtifactListElementResponseModel.attributeTypeMap;
    }
}

