/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class V0AvatarPromoteResponseItemModel {
    'isCandidate'?: boolean;
    'slug'?: string;
    'uploadFileName'?: string;
    'uploadFileSize'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isCandidate",
            "baseName": "is_candidate",
            "type": "boolean"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        },
        {
            "name": "uploadFileName",
            "baseName": "upload_file_name",
            "type": "string"
        },
        {
            "name": "uploadFileSize",
            "baseName": "upload_file_size",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return V0AvatarPromoteResponseItemModel.attributeTypeMap;
    }
}

