/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { V0BuildParamsEnvironment } from './v0BuildParamsEnvironment';
import { V0CommitPaths } from './v0CommitPaths';

export class V0BuildTriggerParamsBuildParams {
    'branch'?: string;
    'branchDest'?: string;
    'branchDestRepoOwner'?: string;
    'branchRepoOwner'?: string;
    'buildRequestSlug'?: string;
    'commitHash'?: string;
    'commitMessage'?: string;
    'commitPaths'?: Array<V0CommitPaths>;
    'diffUrl'?: string;
    'environments'?: Array<V0BuildParamsEnvironment>;
    'pullRequestAuthor'?: string;
    'pullRequestHeadBranch'?: string;
    'pullRequestId'?: object;
    'pullRequestMergeBranch'?: string;
    'pullRequestRepositoryUrl'?: string;
    'skipGitStatusReport'?: boolean;
    'tag'?: string;
    'workflowId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "branch",
            "baseName": "branch",
            "type": "string"
        },
        {
            "name": "branchDest",
            "baseName": "branch_dest",
            "type": "string"
        },
        {
            "name": "branchDestRepoOwner",
            "baseName": "branch_dest_repo_owner",
            "type": "string"
        },
        {
            "name": "branchRepoOwner",
            "baseName": "branch_repo_owner",
            "type": "string"
        },
        {
            "name": "buildRequestSlug",
            "baseName": "build_request_slug",
            "type": "string"
        },
        {
            "name": "commitHash",
            "baseName": "commit_hash",
            "type": "string"
        },
        {
            "name": "commitMessage",
            "baseName": "commit_message",
            "type": "string"
        },
        {
            "name": "commitPaths",
            "baseName": "commit_paths",
            "type": "Array<V0CommitPaths>"
        },
        {
            "name": "diffUrl",
            "baseName": "diff_url",
            "type": "string"
        },
        {
            "name": "environments",
            "baseName": "environments",
            "type": "Array<V0BuildParamsEnvironment>"
        },
        {
            "name": "pullRequestAuthor",
            "baseName": "pull_request_author",
            "type": "string"
        },
        {
            "name": "pullRequestHeadBranch",
            "baseName": "pull_request_head_branch",
            "type": "string"
        },
        {
            "name": "pullRequestId",
            "baseName": "pull_request_id",
            "type": "object"
        },
        {
            "name": "pullRequestMergeBranch",
            "baseName": "pull_request_merge_branch",
            "type": "string"
        },
        {
            "name": "pullRequestRepositoryUrl",
            "baseName": "pull_request_repository_url",
            "type": "string"
        },
        {
            "name": "skipGitStatusReport",
            "baseName": "skip_git_status_report",
            "type": "boolean"
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string"
        },
        {
            "name": "workflowId",
            "baseName": "workflow_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0BuildTriggerParamsBuildParams.attributeTypeMap;
    }
}

