/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class V0BuildAbortParams {
    'abortReason'?: string;
    'abortWithSuccess'?: boolean;
    'skipNotifications'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "abortReason",
            "baseName": "abort_reason",
            "type": "string"
        },
        {
            "name": "abortWithSuccess",
            "baseName": "abort_with_success",
            "type": "boolean"
        },
        {
            "name": "skipNotifications",
            "baseName": "skip_notifications",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return V0BuildAbortParams.attributeTypeMap;
    }
}

