/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { V0AppResponseItemModel } from './v0AppResponseItemModel';

export class V0BuildListAllResponseItemModel {
    'abortReason'?: string;
    'branch'?: string;
    'buildNumber'?: number;
    'commitHash'?: string;
    'commitMessage'?: string;
    'commitViewUrl'?: string;
    'environmentPrepareFinishedAt'?: string;
    'finishedAt'?: string;
    'isOnHold'?: boolean;
    'machineTypeId'?: string;
    'originalBuildParams'?: string;
    'pullRequestId'?: number;
    'pullRequestTargetBranch'?: string;
    'pullRequestViewUrl'?: string;
    'repository'?: V0AppResponseItemModel;
    'slug'?: string;
    'stackIdentifier'?: string;
    'startedOnWorkerAt'?: string;
    'status'?: number;
    'statusText'?: string;
    'tag'?: string;
    'triggeredAt'?: string;
    'triggeredBy'?: string;
    'triggeredWorkflow'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "abortReason",
            "baseName": "abort_reason",
            "type": "string"
        },
        {
            "name": "branch",
            "baseName": "branch",
            "type": "string"
        },
        {
            "name": "buildNumber",
            "baseName": "build_number",
            "type": "number"
        },
        {
            "name": "commitHash",
            "baseName": "commit_hash",
            "type": "string"
        },
        {
            "name": "commitMessage",
            "baseName": "commit_message",
            "type": "string"
        },
        {
            "name": "commitViewUrl",
            "baseName": "commit_view_url",
            "type": "string"
        },
        {
            "name": "environmentPrepareFinishedAt",
            "baseName": "environment_prepare_finished_at",
            "type": "string"
        },
        {
            "name": "finishedAt",
            "baseName": "finished_at",
            "type": "string"
        },
        {
            "name": "isOnHold",
            "baseName": "is_on_hold",
            "type": "boolean"
        },
        {
            "name": "machineTypeId",
            "baseName": "machine_type_id",
            "type": "string"
        },
        {
            "name": "originalBuildParams",
            "baseName": "original_build_params",
            "type": "string"
        },
        {
            "name": "pullRequestId",
            "baseName": "pull_request_id",
            "type": "number"
        },
        {
            "name": "pullRequestTargetBranch",
            "baseName": "pull_request_target_branch",
            "type": "string"
        },
        {
            "name": "pullRequestViewUrl",
            "baseName": "pull_request_view_url",
            "type": "string"
        },
        {
            "name": "repository",
            "baseName": "repository",
            "type": "V0AppResponseItemModel"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        },
        {
            "name": "stackIdentifier",
            "baseName": "stack_identifier",
            "type": "string"
        },
        {
            "name": "startedOnWorkerAt",
            "baseName": "started_on_worker_at",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        },
        {
            "name": "statusText",
            "baseName": "status_text",
            "type": "string"
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string"
        },
        {
            "name": "triggeredAt",
            "baseName": "triggered_at",
            "type": "string"
        },
        {
            "name": "triggeredBy",
            "baseName": "triggered_by",
            "type": "string"
        },
        {
            "name": "triggeredWorkflow",
            "baseName": "triggered_workflow",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0BuildListAllResponseItemModel.attributeTypeMap;
    }
}

