/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class V0BuildTriggerRespModel {
    'buildNumber'?: number;
    'buildSlug'?: string;
    'buildUrl'?: string;
    'message'?: string;
    'service'?: string;
    'slug'?: string;
    'status'?: string;
    'triggeredWorkflow'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "buildNumber",
            "baseName": "build_number",
            "type": "number"
        },
        {
            "name": "buildSlug",
            "baseName": "build_slug",
            "type": "string"
        },
        {
            "name": "buildUrl",
            "baseName": "build_url",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "service",
            "baseName": "service",
            "type": "string"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "triggeredWorkflow",
            "baseName": "triggered_workflow",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0BuildTriggerRespModel.attributeTypeMap;
    }
}

