/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class V0BuildCertificateUpdateParams {
    'certificatePassword'?: string;
    'isExpose'?: boolean;
    'isProtected'?: boolean;
    'processed'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "certificatePassword",
            "baseName": "certificate_password",
            "type": "string"
        },
        {
            "name": "isExpose",
            "baseName": "is_expose",
            "type": "boolean"
        },
        {
            "name": "isProtected",
            "baseName": "is_protected",
            "type": "boolean"
        },
        {
            "name": "processed",
            "baseName": "processed",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return V0BuildCertificateUpdateParams.attributeTypeMap;
    }
}

