/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { V0BuildTriggerParamsBuildParams } from './v0BuildTriggerParamsBuildParams';
import { V0BuildTriggerParamsHookInfo } from './v0BuildTriggerParamsHookInfo';

export class V0BuildTriggerParams {
    'buildParams'?: V0BuildTriggerParamsBuildParams;
    'hookInfo'?: V0BuildTriggerParamsHookInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "buildParams",
            "baseName": "build_params",
            "type": "V0BuildTriggerParamsBuildParams"
        },
        {
            "name": "hookInfo",
            "baseName": "hook_info",
            "type": "V0BuildTriggerParamsHookInfo"
        }    ];

    static getAttributeTypeMap() {
        return V0BuildTriggerParams.attributeTypeMap;
    }
}

