/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { V0BuildLogChunkItemResponseModel } from './v0BuildLogChunkItemResponseModel';

export class V0BuildLogInfoResponseModel {
    'expiringRawLogUrl'?: string;
    'generatedLogChunksNum'?: number;
    'isArchived'?: boolean;
    'logChunks'?: Array<V0BuildLogChunkItemResponseModel>;
    'timestamp'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expiringRawLogUrl",
            "baseName": "expiring_raw_log_url",
            "type": "string"
        },
        {
            "name": "generatedLogChunksNum",
            "baseName": "generated_log_chunks_num",
            "type": "number"
        },
        {
            "name": "isArchived",
            "baseName": "is_archived",
            "type": "boolean"
        },
        {
            "name": "logChunks",
            "baseName": "log_chunks",
            "type": "Array<V0BuildLogChunkItemResponseModel>"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0BuildLogInfoResponseModel.attributeTypeMap;
    }
}

