/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { V0OrganizationOwner } from './v0OrganizationOwner';

export class V0OrganizationDataModel {
    'avatarIconUrl'?: string;
    'concurrencyCount'?: number;
    'name'?: string;
    'owners'?: Array<V0OrganizationOwner>;
    'slug'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avatarIconUrl",
            "baseName": "avatar_icon_url",
            "type": "string"
        },
        {
            "name": "concurrencyCount",
            "baseName": "concurrency_count",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "owners",
            "baseName": "owners",
            "type": "Array<V0OrganizationOwner>"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0OrganizationDataModel.attributeTypeMap;
    }
}

