/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { V0AddOnAppResponseItemModel } from './v0AddOnAppResponseItemModel';

export class V0OwnerAddOnResponseItemModel {
    'apps'?: Array<V0AddOnAppResponseItemModel>;
    'documentationUrl'?: string;
    'hasUi'?: boolean;
    'icon'?: string;
    'id'?: string;
    'isBeta'?: boolean;
    'summary'?: string;
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apps",
            "baseName": "apps",
            "type": "Array<V0AddOnAppResponseItemModel>"
        },
        {
            "name": "documentationUrl",
            "baseName": "documentation_url",
            "type": "string"
        },
        {
            "name": "hasUi",
            "baseName": "has_ui",
            "type": "boolean"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "isBeta",
            "baseName": "is_beta",
            "type": "boolean"
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0OwnerAddOnResponseItemModel.attributeTypeMap;
    }
}

