/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class V0ProjectFileStorageResponseItemModel {
    'downloadUrl'?: string;
    'exposedMetaDatastore'?: string;
    'isExpose'?: boolean;
    'isProtected'?: boolean;
    'processed'?: boolean;
    'slug'?: string;
    'uploadFileName'?: string;
    'uploadFileSize'?: number;
    'uploadUrl'?: string;
    'userEnvKey'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "downloadUrl",
            "baseName": "download_url",
            "type": "string"
        },
        {
            "name": "exposedMetaDatastore",
            "baseName": "exposed_meta_datastore",
            "type": "string"
        },
        {
            "name": "isExpose",
            "baseName": "is_expose",
            "type": "boolean"
        },
        {
            "name": "isProtected",
            "baseName": "is_protected",
            "type": "boolean"
        },
        {
            "name": "processed",
            "baseName": "processed",
            "type": "boolean"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        },
        {
            "name": "uploadFileName",
            "baseName": "upload_file_name",
            "type": "string"
        },
        {
            "name": "uploadFileSize",
            "baseName": "upload_file_size",
            "type": "number"
        },
        {
            "name": "uploadUrl",
            "baseName": "upload_url",
            "type": "string"
        },
        {
            "name": "userEnvKey",
            "baseName": "user_env_key",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0ProjectFileStorageResponseItemModel.attributeTypeMap;
    }
}

