/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class V0ProjectFileStorageUploadParams {
    'uploadFileName'?: string;
    'uploadFileSize'?: number;
    'userEnvKey'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uploadFileName",
            "baseName": "upload_file_name",
            "type": "string"
        },
        {
            "name": "uploadFileSize",
            "baseName": "upload_file_size",
            "type": "number"
        },
        {
            "name": "userEnvKey",
            "baseName": "user_env_key",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0ProjectFileStorageUploadParams.attributeTypeMap;
    }
}

