/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class V0SSHKeyUploadParams {
    /**
    * The private part of the SSH key you would like to use
    */
    'authSshPrivateKey'?: string;
    /**
    * The public part of the SSH key you would like to use
    */
    'authSshPublicKey'?: string;
    /**
    * If it\'s set to true, the provided SSH key will be registered at the provider of the application
    */
    'isRegisterKeyIntoProviderService'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "authSshPrivateKey",
            "baseName": "auth_ssh_private_key",
            "type": "string"
        },
        {
            "name": "authSshPublicKey",
            "baseName": "auth_ssh_public_key",
            "type": "string"
        },
        {
            "name": "isRegisterKeyIntoProviderService",
            "baseName": "is_register_key_into_provider_service",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return V0SSHKeyUploadParams.attributeTypeMap;
    }
}

