/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { V0PlanDataModel } from './v0PlanDataModel';

export class V0UserPlanDataModel {
    'currentPlan'?: V0PlanDataModel;
    'pendingPlan'?: V0PlanDataModel;
    'trialExpiresAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currentPlan",
            "baseName": "current_plan",
            "type": "V0PlanDataModel"
        },
        {
            "name": "pendingPlan",
            "baseName": "pending_plan",
            "type": "V0PlanDataModel"
        },
        {
            "name": "trialExpiresAt",
            "baseName": "trial_expires_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0UserPlanDataModel.attributeTypeMap;
    }
}

