/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class V0WebhookDeliveryItemResponseModel {
    'createdAt'?: string;
    'requestHeaders'?: string;
    'requestPayload'?: string;
    'requestUrl'?: string;
    'responseBody'?: string;
    'responseHeaders'?: string;
    'responseHttpStatus'?: string;
    'responseSeconds'?: string;
    'slug'?: string;
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "requestHeaders",
            "baseName": "request_headers",
            "type": "string"
        },
        {
            "name": "requestPayload",
            "baseName": "request_payload",
            "type": "string"
        },
        {
            "name": "requestUrl",
            "baseName": "request_url",
            "type": "string"
        },
        {
            "name": "responseBody",
            "baseName": "response_body",
            "type": "string"
        },
        {
            "name": "responseHeaders",
            "baseName": "response_headers",
            "type": "string"
        },
        {
            "name": "responseHttpStatus",
            "baseName": "response_http_status",
            "type": "string"
        },
        {
            "name": "responseSeconds",
            "baseName": "response_seconds",
            "type": "string"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0WebhookDeliveryItemResponseModel.attributeTypeMap;
    }
}

